import AppKit
import Observation

/// Watches the general pasteboard and keeps a `ClipHistory`.
///
/// Polling is the only option on macOS — there is no change notification —
/// and it is cheap: one integer read twice a second, and nothing else is read
/// until that counter moves.
///
/// **What is never recorded:**
/// - copies marked concealed / transient / auto-generated (nspasteboard.org
///   conventions; password managers set these),
/// - copies made while an excluded app is frontmost (Preferences),
/// - our own writes (`myHubOwnWrite`),
/// - very large text (it would bloat memory and the sealed file).
@MainActor
@Observable
final class PasteboardMonitor {
    private(set) var history: ClipHistory
    /// The search field's text.
    var query = ""

    /// Pinned first, then newest; narrowed by the search.
    var visibleEntries: [ClipEntry] {
        let ordered = history.pinned + history.recent
        let needle = query.trimmingCharacters(in: .whitespaces)
        guard !needle.isEmpty else { return ordered }
        return ordered.filter {
            $0.preview.localizedCaseInsensitiveContains(needle) || ($0.source?.localizedCaseInsensitiveContains(needle) ?? false)
        }
    }

    /// Image data found on the pasteboard, already PNG. The receiver saves it
    /// and calls `recordCapture`.
    @ObservationIgnored var onImage: ((Data) -> Void)?

    @ObservationIgnored private let preferences: Preferences
    /// `.general` in the app; a private named pasteboard in tests.
    @ObservationIgnored private let pasteboard: NSPasteboard
    @ObservationIgnored private let sampler = Ticker()
    @ObservationIgnored private var lastChangeCount: Int
    @ObservationIgnored private var imageWait: Task<Void, Never>?
    @ObservationIgnored private let saves = WriteCoalescer(delay: .seconds(2))
    @ObservationIgnored private var restored = false

    static let maxTextBytes = 512 * 1024
    /// Markers a copying app adds to say "keep this out of any history".
    private static let doNotRecord: Set<String> = Set(
        ["Concealed", "Transient", "AutoGenerated"].map { "org.nspasteboard.\($0)Type" }
    )
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    init(preferences: Preferences, pasteboard: NSPasteboard = .general) {
        self.preferences = preferences
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
        history = ClipHistory(limit: preferences.values.clipboard.historyLimit)
    }

    private var settings: Preferences.Clipboard { preferences.values.clipboard }

    // MARK: - Lifecycle

    func start() {
        restoreIfNeeded()
        if sampler.isRunning { return }
        lastChangeCount = pasteboard.changeCount
        // Twice a second feels instant when you open the panel right after
        // copying; the counter read is too cheap to matter.
        sampler.run(every: 0.5, slack: 0.4) { [weak self] in self?.poll() }
    }

    func stop() {
        sampler.halt()
        imageWait?.cancel()
        imageWait = nil
        // Quitting: write synchronously, a background task would not finish.
        if saves.hasPendingWrite {
            saves.cancel()
            if settings.persistHistory { HistoryVault.write(history) }
        }
    }

    // MARK: - User actions

    func copy(_ id: UUID) {
        guard let entry = history.entries.first(where: { $0.id == id }) else { return }
        pasteboard.clearContents()
        switch entry.content {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .files(let urls):
            pasteboard.writeObjects(urls.map { $0 as NSURL })
        }
        pasteboard.setData(Data(), forType: .myHubOwnWrite)
        lastChangeCount = pasteboard.changeCount
        mutate { $0.promote(id, at: Date()) }
    }

    /// Puts text MyHub produced (a transformed entry, an expanded snippet) on
    /// the pasteboard. With `record`, it also goes to the top of the history.
    func copyText(_ text: String, record: Bool) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setData(Data(), forType: .myHubOwnWrite)
        lastChangeCount = pasteboard.changeCount
        if record { mutate { $0.record(.text(text), at: Date(), source: "MyHub") } }
    }

    func togglePin(_ id: UUID) { mutate { $0.togglePin(id) } }
    func remove(_ id: UUID) { mutate { $0.remove(id) } }
    func clear() { mutate { $0.clearUnpinned() } }

    func recordCapture(_ url: URL) {
        mutate { $0.record(.files([url]), at: Date(), source: nil) }
    }

    #if DEBUG
    /// Previews and snapshots only: (text, source app, seconds ago), newest last.
    func injectForPreview(_ entries: [(String, String, TimeInterval)], now: Date) {
        for (text, source, ago) in entries.reversed() {
            history.record(.text(text), at: now.addingTimeInterval(-ago), source: source)
        }
    }
    #endif

    func setPersistence(_ on: Bool) {
        preferences.update { $0.clipboard.persistHistory = on }
        if on {
            scheduleSave()
        } else {
            saves.cancel()
            Task.detached(priority: .utility) { HistoryVault.erase() }
        }
    }

    // MARK: - Polling

    /// One sample. Internal so tests can drive it without the timer.
    func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        imageWait?.cancel()

        let types = pasteboard.types ?? []
        if types.contains(.myHubOwnWrite) { return }
        if types.contains(where: { Self.doNotRecord.contains($0.rawValue) }) { return }
        let frontmost = NSWorkspace.shared.frontmostApplication
        let declaredSource = pasteboard.string(forType: Self.sourceType)
        let excluded = Set(settings.excludedBundleIDs)
        if let id = frontmost?.bundleIdentifier, excluded.contains(id) { return }
        if let declaredSource, excluded.contains(declaredSource) { return }
        let source = frontmost?.localizedName

        let files = Self.fileURLs(on: pasteboard)
        if !files.isEmpty {
            record(.files(files), source: source)
            return
        }
        if settings.saveImagesToStash, pasteboard.availableType(from: [.png, .tiff]) != nil {
            awaitImage(changeCount: count, source: source)
            return
        }
        recordText(from: pasteboard, source: source)
    }

    /// One file URL per pasteboard item; Finder puts each copied file in an
    /// item of its own.
    private static func fileURLs(on pasteboard: NSPasteboard) -> [URL] {
        (pasteboard.pasteboardItems ?? []).compactMap { item in
            item.string(forType: .fileURL).flatMap(URL.init(string:)).flatMap { $0.isFileURL ? $0 : nil }
        }
    }

    private func recordText(from pasteboard: NSPasteboard, source: String?) {
        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.utf8.count <= Self.maxTextBytes else { return }
        record(.text(text), source: source)
    }

    /// An image copied on an iPhone arrives in two steps over Continuity: the
    /// type appears at once, the bytes a moment later. Keep checking for a few
    /// seconds, and give up as soon as something newer is copied — finishing a
    /// superseded transfer would record the wrong thing.
    private func awaitImage(changeCount: Int, source: String?) {
        imageWait = Task { [weak self] in
            for _ in 0..<12 {
                guard let pasteboard = self?.pasteboard, pasteboard.changeCount == changeCount, !Task.isCancelled else { return }
                if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
                    guard let png = await ImageEncoding.png(from: data), !Task.isCancelled else { return }
                    self?.onImage?(png)
                    return
                }
                try? await Task.sleep(for: .milliseconds(500))
            }
            // Offered a picture, never delivered one: keep the text beside it.
            guard let pasteboard = self?.pasteboard, pasteboard.changeCount == changeCount else { return }
            self?.recordText(from: pasteboard, source: source)
        }
    }

    // MARK: - State

    private func record(_ content: ClipContent, source: String?) {
        mutate { $0.record(content, at: Date(), source: source) }
    }

    private func mutate(_ change: (inout ClipHistory) -> Void) {
        var next = history
        next.setLimit(settings.historyLimit)
        change(&next)
        guard next != history else { return }
        history = next
        scheduleSave()
    }

    private func scheduleSave() {
        guard settings.persistHistory else { return }
        saves.schedule { [weak self] in
            guard let snapshot = self?.history else { return }
            Task.detached(priority: .utility) { HistoryVault.write(snapshot) }
        }
    }

    private func restoreIfNeeded() {
        guard !restored else { return }
        restored = true
        guard settings.persistHistory, let stored = HistoryVault.read() else { return }
        var merged = stored
        merged.setLimit(settings.historyLimit)
        history = merged
    }
}

/// Pasteboard images arrive as PNG or TIFF; the stash keeps PNG. Converting a
/// large TIFF is real work, so it happens off the main actor.
enum ImageEncoding {
    static func png(from data: Data) async -> Data? {
        await Task.detached(priority: .userInitiated) {
            if data.starts(with: [0x89, 0x50, 0x4E, 0x47]) { return data }
            return NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:])
        }.value
    }
}
